### ISSUE TITLE
Tried to install this addon on Anki 2.1.22

### ISSUE THREAD

**Issue by Willz7** [ig3/anki-limitnew#1]
Hi, 

I tried to install this addon on Anki 2.1.22 to see if it works on 2.1.22. 
![GitHub Logo](https://i.imgur.com/okKhf8c.png)
This is the error I got not sure how I can solve this. I know that you put Anki requirement to 2.1.26 to use this Addon. Wanted to see if it is possible to use it.

Thank you for all the work and updates.

**Comment by ig3** [comment]
It updated successfully for me, but requirements must be a bit different for a fresh install. I will be away for a few days but will look at this when I get back.

**Comment by ig3** [comment]
I added manifest.json. After this, I was able to delete and re-install the add on from file (limitnew.ankiaddon) and also update it from ankiweb to 2.1.26. Maybe this will suffice also for 2.1.22. Thanks for testing and letting me know the problem.

**Comment by ig3** [comment]
I believe adding the manifest resolves the problem and have no indication to the contrary in three months, but feel free to re-open this issue if there is still a problem.
